apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: darts-league
data:
  SPRING_DATA_MONGODB_HOST: "mongodb"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "darts_league"
  FILE_UPLOAD_DIR: "/app/uploads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: darts-league
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: darts-league
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: copy-initial-photos
          image: itonkdong/darts-league-backend:latest
          command:
            - sh
            - -c
            - |
              echo "Creating directory structure..."
              mkdir -p /data/player_photos
              mkdir -p /data/winner_photos
              
              # Copy photos
              echo "Copying photos..."
              cp -v /app/uploads/player_photos/* /data/player_photos/ 2>/dev/null || echo "Not found at path 3"
              cp -v /app/uploads/winner_photos/* /data/winner_photos/ 2>/dev/null || echo "Not found at path 3"
              
              # Check where the files in the image actually are by searching recursively
              echo "Searching for image files recursively..."
              find /app -name "*.png" | grep -E 'player_photos|winner_photos' 2>/dev/null || echo "No image files found"
              
              echo "Copied files to destination:"
              ls -la /data/player_photos/
              ls -la /data/winner_photos/
          volumeMounts:
            - name: uploads-data
              mountPath: /data
      containers:
      - name: backend
        image: itonkdong/darts-league-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
        volumeMounts:
        - name: uploads-data
          mountPath: /app/uploads
      volumes:
      - name: uploads-data
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: darts-league
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
